version: "3.8"
   
services:
  http:
    image: vladoplavsic/http
    ports:
      - "8000:8000"
  db:
    image: vladoplavsic/postgres
    environment:
      - POSTGRES_DB=admin
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
  web:
    image: vladoplavsic/restlin
    ports:
      - "1337:1337"
    depends_on:
      - db

